Helpful error message from humans when config.sh does not exist
Closes #3

diff --git a/humans b/humans
--- a/humans
+++ b/humans
@@ -1,10 +1,14 @@
 #!/bin/sh
 
-# Load configuration file
-source "$(dirname $0)/config.sh"
-
 # Exit script on errors
 set -ue
+
+# Load configuration file
+if ! (source config.sh 2> /dev/null); then
+  echo >&2 "Could not find $(dirname "$0")/config.sh"
+  echo >&2 "Run $(dirname "$0")/configure to create it"
+  exit 1
+fi
 
 # Create a temporary directory to store the repository
 dir="$(mktemp -d)"
